//
//  FlickrAPI.swift
//  Photorama
//
//  Created by Matthew Olker on 4/19/17.
//  Copyright © 2017 Matthew Olker. All rights reserved.
// responsible for knowing and handling all Flickr-related information

import Foundation
import CoreData

//reprsents possible errors for Flickr API
enum FlickrError: Error {
    case invalidJSONData
}

//specifys which endpoint on the Flickr server to hit
// matches corresponding Flickr endpoint
enum Method: String {
    case interestingPhotos = "flickr.interestingness.getList"
}

struct FlickrAPI {
    //reference the base URL string for the web service requests
    private static let baseURLString = "https://api.flickr.com/services/rest"
    //a token generated by Flickr to identify the application and authenticate it with the web service
    private static let apiKey = "a6d819499131071f158fd740860a5a88"
    
    //converts the datetaken string into an instance of Date
    private static let dateFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyy-MM-dd HH:mm:ss"
        return formatter
    }()
    
    //this method parses a JSON dictionary into a photo instance
    private static func photo(fromJSON json: [String : Any], into context: NSManagedObjectContext) -> Photo? {
        guard
            let photoID = json["id"] as? String,
            let title = json["title"] as? String,
            let dateString = json["datetaken"] as? String,
            let photoURLString = json["url_h"] as? String,
            let url = URL(string: photoURLString),
            let dateTaken = dateFormatter.date(from: dateString) else {
                
                //Don't have enough information to construct a Photo
                return nil
        }
        
        //checks whether or not there is an existing photo with the given ID
        let fetchRequest: NSFetchRequest<Photo> = Photo.fetchRequest()
        let predicate = NSPredicate(format: "\(#keyPath(Photo.photoID)) == \(photoID)")
        fetchRequest.predicate = predicate
        
        var fetchedPhotos: [Photo]?
        context.performAndWait {
            fetchedPhotos = try? fetchRequest.execute()
        }
        if let existingPhoto = fetchedPhotos?.first {
            return existingPhoto
        }
        
        var photo: Photo!
        context.performAndWait {
            photo = Photo(context: context)
            photo.title = title
            photo.photoID = photoID
            photo.remoteURL = url as NSURL
            photo.dateTaken = dateTaken as NSDate
            //code for Bronze Challenge: Photo View Count
            photo.viewCount = 0
        }
        
        return photo
    }
    
    //helps to construct the full URL
    private static func flickrURL(method: Method, parameters: [String:String]?) -> URL {
        var components = URLComponents(string: baseURLString)!
        
        var queryItems = [URLQueryItem]()
        
        let baseParams = [
            "method": method.rawValue,
            "format": "json",
            "nojsoncallback": "1",
            "api_key": apiKey
        ]
        
        for (key, value) in baseParams {
            let item = URLQueryItem(name: key, value: value)
            queryItems.append(item)
        }
        
        if let additionalParams = parameters {
            for (key,value) in additionalParams {
                let item = URLQueryItem(name: key, value: value)
                queryItems.append(item)
            }
        }
        components.queryItems = queryItems
        
        return components.url!
    }
    
    //internal type method exposed to the project for each of the specific endpoint URLs
    static var interestingPhotosURL: URL {
        
        return flickrURL(method: .interestingPhotos, parameters: ["extras": "url_h, date_taken"])
        
    }
    
    //takes in an instance of Data and uses the JSONSerialization class to convert the data into basic foundation objects
    //gets the array of dictionaries representing individual photos found by the function
    //parses dictionaries into Photo instances then return them as part of the success enumerator
    static func photos(fromJson data: Data, into context: NSManagedObjectContext) -> PhotosResult {
        do {
            let jsonObject = try JSONSerialization.jsonObject(with: data, options: [])
            
            guard
                let jsonDictionary = jsonObject as? [AnyHashable:Any],
                let photos = jsonDictionary["photos"] as? [String:Any],
                let photosArray = photos["photo"] as? [[String:Any]] else {
                    
                    //The JSON structure doesn't match our expectations
                    return .failure(FlickrError.invalidJSONData)
            }
            
            var finalPhotos = [Photo]()
            for photoJSON in photosArray {
                if let photo = photo(fromJSON: photoJSON, into: context) {
                    finalPhotos.append(photo)
                }
            }
            
            if finalPhotos.isEmpty && !photosArray.isEmpty {
                //We weren't able to parse any of the photos
                //Maybe the JSON formate for photos has changed
                return .failure(FlickrError.invalidJSONData)
            }
            
            
            return .success(finalPhotos)
        } catch let error {
            return .failure(error)
        }
    }
    
}



